### ISSUE TITLE
Geocode not happening

### ISSUE THREAD

**Issue by alankessler** [adamfast/faadata#4]
Postgis import worked fine, but I am unable to figure out how to geocode the aircraft records. Any chance you could spell that out in the docs, please?

**Comment by adamfast** [comment]
@alankessler Geocoding isn't explicitly supported (and for many aircraft types, registered by holding companies would just be flat wrong)

It would be entirely POSSIBLE to geocode them, modifying the examples I blogged about in http://blog.adamfast.com/2011/11/geocoding-turning-text-into-numbers/ (if I was going to be doing it, I'd be using GeoPy as it abstracts a lot of options of geocoders. You'll need to consider cost, data restrictions that come along with the geocoder, and pick one that works for you.)

I'm going to close this as invalid for the reasons above.
